const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STYLE={manhwa:'full-color Korean webtoon aesthetic, clean line art, polished cel shading, cinematic dramatic lighting, detailed environments',action:'black and white action manga, bold ink lines, screentones, dynamic motion, impact framing',seinen:'cinematic detailed manga, realistic anatomy, nuanced expressions, textured shadows, mature visual storytelling',romance:'elegant romantic manga, soft lighting, expressive eyes, delicate line work, emotional atmosphere',horror:'psychological horror manga, heavy black ink, unsettling composition, dramatic high contrast, eerie atmosphere',dark:'dark fantasy manga, epic scale, intricate armor and environments, moody dramatic lighting, textured illustration'};
const SHOTS=['Wide establishing','Medium','Close-up','Extreme close-up','Full body','Over shoulder'];
const ANGLES=['Eye level','Low angle','High angle','Dutch angle','Bird’s-eye','Ground level'];
const MOODS=['Neutral','Tense','Triumphant','Mysterious','Sad','Romantic','Terrifying','Comedic'];
const common=new Set(['The','A','An','I','He','She','They','We','It','His','Her','Their','This','That','When','After','Before','But','And','Then','Suddenly','Meanwhile','Later','Chapter']);
let state={name:'Untitled story',story:'',style:'manhwa',characters:[],scenes:[],panels:[],images:{},cover:null,version:1};
let imageKey=sessionStorage.getItem('qt-image-key')||new URLSearchParams(location.search).get('imageKey')||'';
let connected=false,busy=false,editing=null;
const example=`Jin woke beneath the ruins of a city he had never seen. A silver mark burned across his left hand.\n\nAt the broken station, Mira found him first. She wore a long red coat and carried a sword wrapped in black cloth. She warned Jin that the creatures hunting him could smell fear.\n\nA shadow beast crashed through the ceiling. Jin raised his marked hand, and blue light exploded across the platform. Mira stared at him in disbelief. “So the stories were true.”`;
function uid(prefix='id'){return prefix+'-'+crypto.randomUUID().slice(0,8)}
function status(msg){$('#status').textContent=msg}
function escapeHtml(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function debounce(fn,ms=350){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
function save(){state.name=$('#projectName').value.trim()||'Untitled story';state.story=$('#story').value;localStorage.setItem('qt-manga-project',JSON.stringify(state));$('#saveStatus').textContent='Saved on this device · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
const autosave=debounce(save,500);
function load(){try{const raw=localStorage.getItem('qt-manga-project');if(raw)state={...state,...JSON.parse(raw)};}catch{} $('#projectName').value=state.name;$('#story').value=state.story;selectStyle(state.style);renderAll()}
function words(s){return (s.match(/[\p{L}\p{N}]+/gu)||[]).length}
function splitScenes(text){return text.split(/\n\s*\n|(?<=[.!?])\s+(?=[A-Z][^.!?]{40,})/g).map(s=>s.trim()).filter(Boolean).flatMap(s=>s.length>900?s.match(/.{1,850}(?:\s|$)/gs).map(x=>x.trim()):[s]);}
function extractCharacters(text){const counts=new Map();for(const m of text.matchAll(/\b[A-Z][a-z]{2,}\b/g)){const n=m[0];if(common.has(n))continue;counts.set(n,(counts.get(n)||0)+1)}return [...counts].filter(([,n])=>n>=2).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([name])=>({id:uid('char'),name,role:'Character',description:'',outfit:'',traits:'',locked:false,reference:null,seed:Math.floor(Math.random()*2**31)}));}
function analyze(){const text=$('#story').value.trim();if(!text)return status('Paste a story first.');state.story=text;const existing=new Map(state.characters.map(c=>[c.name.toLowerCase(),c]));const found=extractCharacters(text);state.characters=found.map(c=>existing.get(c.name.toLowerCase())||c);const chunks=splitScenes(text);state.scenes=chunks.map((text,i)=>({id:uid('scene'),title:'Scene '+(i+1),text}));state.panels=chunks.map((text,i)=>makePanel(text,i));renderAll();go('cast');save();status('Story analyzed. Review the cast, then lock reference looks.');}
function makePanel(text,i){const names=state.characters.filter(c=>new RegExp('\\b'+c.name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','i').test(text)).map(c=>c.id);return{id:uid('panel'),scene:i+1,source:text,shot:i%3===0?'Wide establishing':i%3===1?'Medium':'Close-up',angle:i%4===0?'Low angle':'Eye level',mood:'Neutral',characters:names,prompt:text,dialogue:'',sfx:'',seed:Math.floor(Math.random()*2**31),ref:0.7};}
function go(step){$$('.stage').forEach(b=>b.classList.toggle('active',b.dataset.step===step));$$('.step-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===step));if(step==='draw')renderDraw();if(step==='export')renderExport();}
function renderAll(){renderStats();renderScenes();renderCast();renderLayout();renderDraw();renderExport()}
function renderStats(){$('#storyStats').textContent=words($('#story').value)+' words';$('#sceneCount').textContent=state.scenes.length;$('#characterCount').textContent=state.characters.length;$('#panelCount').textContent=state.panels.length}
function renderScenes(){const root=$('#storyScenes');root.replaceChildren();state.scenes.forEach((s,i)=>{const d=document.createElement('article');d.className='scene';d.innerHTML=`<h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.text.slice(0,190))}${s.text.length>190?'…':''}</p><span class="note">Panel ${i+1}</span>`;root.append(d)})}
function charCard(c){const d=document.createElement('article');d.className='character'+(c.locked?' locked':'');d.dataset.id=c.id;d.innerHTML=`${c.reference?`<img src="${c.reference}" alt="${escapeHtml(c.name)} reference">`:`<div class="empty-art">Reference sheet<br>not set</div>`}<div class="fields"><div class="two"><div class="field"><label>Name</label><input data-k="name" value="${escapeHtml(c.name)}"></div><div class="field"><label>Role</label><input data-k="role" value="${escapeHtml(c.role)}"></div></div><div class="field"><label>Appearance</label><textarea data-k="description" rows="3" placeholder="Hair, face, age, build, distinctive details…">${escapeHtml(c.description)}</textarea></div><div class="field"><label>Outfit & props</label><input data-k="outfit" value="${escapeHtml(c.outfit)}"></div><div class="actions"><label class="chip">Upload ref<input data-ref type="file" accept="image/*" hidden></label><button class="chip" data-genref>Generate sheet</button><button class="chip" data-lock>${c.locked?'✓ Locked':'Lock look'}</button><button class="chip" data-remove>Remove</button></div></div>`;d.querySelectorAll('[data-k]').forEach(el=>el.oninput=()=>{c[el.dataset.k]=el.value;autosave();renderLayout()});d.querySelector('[data-ref]').onchange=async e=>{const f=e.target.files[0];if(!f)return;c.reference=await fileData(f);c.locked=true;renderCast();autosave()};d.querySelector('[data-lock]').onclick=()=>{c.locked=!c.locked;renderCast();autosave()};d.querySelector('[data-remove]').onclick=()=>{state.characters=state.characters.filter(x=>x.id!==c.id);state.panels.forEach(p=>p.characters=p.characters.filter(id=>id!==c.id));renderAll();autosave()};d.querySelector('[data-genref]').onclick=()=>generateReference(c);return d}
function renderCast(){const root=$('#castGrid');root.replaceChildren();state.characters.forEach(c=>root.append(charCard(c)))}
function panelPrompt(p){const chars=p.characters.map(id=>state.characters.find(c=>c.id===id)).filter(Boolean);const charText=chars.map(c=>`${c.name}: ${c.description}${c.outfit?`, wearing ${c.outfit}`:''}`).join('. ');return `${STYLE[state.style]}. ${p.shot}, ${p.angle}, ${p.mood.toLowerCase()} mood. ${charText}. Scene: ${p.prompt}. coherent composition, accurate hands, no text, no watermark`;}
function renderLayout(){const root=$('#layoutList');root.replaceChildren();state.panels.forEach((p,i)=>{const d=document.createElement('article');d.className='panel-plan';d.innerHTML=`<div class="head"><h3><span class="number">${i+1}</span>Scene ${p.scene}</h3><button class="chip" data-delete>Delete</button></div><div class="two" style="margin-top:9px"><div class="field"><label>Shot</label><select data-k="shot">${SHOTS.map(v=>`<option ${v===p.shot?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Camera</label><select data-k="angle">${ANGLES.map(v=>`<option ${v===p.angle?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="two"><div class="field"><label>Mood</label><select data-k="mood">${MOODS.map(v=>`<option ${v===p.mood?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Characters</label><select data-char multiple size="${Math.min(4,Math.max(2,state.characters.length))}">${state.characters.map(c=>`<option value="${c.id}" ${p.characters.includes(c.id)?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></div></div><div class="field"><label>Visual direction</label><textarea data-k="prompt" rows="3">${escapeHtml(p.prompt)}</textarea></div><div class="two"><div class="field"><label>Dialogue</label><input data-k="dialogue" value="${escapeHtml(p.dialogue)}"></div><div class="field"><label>SFX</label><input data-k="sfx" value="${escapeHtml(p.sfx)}"></div></div>`;d.querySelectorAll('[data-k]').forEach(el=>el.oninput=()=>{p[el.dataset.k]=el.value;autosave()});const multi=d.querySelector('[data-char]');multi.onchange=()=>{p.characters=[...multi.selectedOptions].map(o=>o.value);autosave()};d.querySelector('[data-delete]').onclick=()=>{state.panels=state.panels.filter(x=>x.id!==p.id);renderAll();autosave()};root.append(d)})}
function autoLayout(){state.panels.forEach((p,i)=>{p.shot=SHOTS[i%SHOTS.length];p.angle=ANGLES[(i*2)%ANGLES.length];p.mood=/fight|attack|battle|crash|explod/i.test(p.source)?'Tense':/love|kiss|heart/i.test(p.source)?'Romantic':/fear|blood|horror|dead/i.test(p.source)?'Terrifying':'Neutral'});renderLayout();autosave();status('Camera direction updated across all panels.')}
function renderDraw(){const root=$('#drawGrid');root.replaceChildren();state.panels.forEach((p,i)=>{const d=document.createElement('article');d.className='panel-card';const img=state.images[p.id];d.innerHTML=`<div class="head"><h3>Panel ${i+1}</h3><span class="note">Seed ${p.seed}</span></div><div class="image-wrap" style="margin-top:8px">${img?`<img src="${img}" alt="Panel ${i+1}">`:`<div class="empty-art">Panel ${i+1}<br>not generated</div>`}<div class="overlay">${p.dialogue?`<div class="bubble">${escapeHtml(p.dialogue)}</div>`:''}${p.sfx?`<div class="sfx">${escapeHtml(p.sfx)}</div>`:''}</div></div><div class="tools"><button class="chip" data-gen>${img?'Regenerate':'Generate'}</button><button class="chip" data-edit>Edit</button>${img?`<button class="chip" data-download>PNG</button>`:''}</div>`;d.querySelector('[data-gen]').onclick=()=>generatePanel(p);d.querySelector('[data-edit]').onclick=()=>openEdit(p);d.querySelector('[data-download]')?.addEventListener('click',()=>downloadPanel(p));root.append(d)})}
function renderExport(){const n=state.panels.filter(p=>state.images[p.id]).length;$('#exportReady').textContent=`${n} / ${state.panels.length} panels ready`}
function selectStyle(id){state.style=id;$$('[data-style]').forEach(b=>b.classList.toggle('active',b.dataset.style===id));autosave()}
async function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function connect(){status('Connecting to local image helper…');try{const res=await fetch(`http://127.0.0.1:8771/health?key=${encodeURIComponent(imageKey)}`,{cache:'no-store'});if(!res.ok)throw new Error('Helper rejected connection');const info=await res.json();connected=true;$('#connection').classList.add('connected');$('#engineTitle').textContent='Connected · '+info.gpu;$('#engineInfo').textContent=`${info.model} · ${info.mode}`;$('#engineDot').textContent='●';$('#engineDot').style.color='var(--green)';status('Image engine ready.');sessionStorage.setItem('qt-image-key',imageKey);}catch(e){connected=false;$('#connection').classList.remove('connected');$('#engineTitle').textContent='Not connected';$('#engineInfo').textContent=e.message||'Start the helper first.';$('#engineDot').textContent='○';status('Start the image helper, then connect again.')}}
async function api(path,payload){if(!connected)await connect();if(!connected)throw new Error('Image helper is not connected.');const res=await fetch(`http://127.0.0.1:8771${path}?key=${encodeURIComponent(imageKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`Generation failed (${res.status})`);return data}
function settings(){const aspect=$('#aspect').value;const [width,height]=aspect==='portrait'?[512,768]:aspect==='landscape'?[768,512]:[512,512];const q=$('#quality').value;return{width,height,steps:q==='fast'?18:q==='high'?34:26,guidance:q==='fast'?6.5:7.5}}
function refsFor(p){if(!$('#consistent').checked)return[];return p.characters.map(id=>state.characters.find(c=>c.id===id)).filter(c=>c?.locked&&c.reference).map(c=>c.reference).slice(0,3)}
async function generatePanel(p){if(busy)return;busy=true;status('Generating panel…');$('#progress').hidden=false;$('#progress').value=18;try{const data=await api('/generate',{prompt:panelPrompt(p),negative:'low quality, blurry, distorted face, extra fingers, malformed hands, duplicate person, text, speech bubble, watermark, logo',seed:p.seed,reference_images:refsFor(p),reference_strength:p.ref??0.7,...settings()});state.images[p.id]=data.image;p.seed=data.seed??p.seed;$('#progress').value=100;renderDraw();renderExport();save();status(`Panel ready · ${data.seconds?.toFixed?.(1)||'?'}s`);}catch(e){status(e.message)}finally{busy=false;setTimeout(()=>$('#progress').hidden=true,500)}}
async function generateReference(c){if(busy)return;busy=true;status('Generating character reference sheet…');try{const s=settings();const data=await api('/generate',{prompt:`character turnaround reference sheet, same person shown front view, three-quarter view and side profile, neutral pose, clean plain background. ${c.name}, ${c.description}, ${c.outfit}. ${STYLE[state.style]}`,negative:'multiple different people, text, watermark, cropped head, deformed',seed:c.seed,width:768,height:512,steps:28,guidance:7.5,reference_images:c.reference?[c.reference]:[],reference_strength:0.75});c.reference=data.image;c.locked=true;renderCast();save();status('Reference sheet generated and locked.');}catch(e){status(e.message)}finally{busy=false}}
async function generateSet(list){for(let i=0;i<list.length;i++){status(`Generating ${i+1} of ${list.length}…`);await generatePanel(list[i]);if(!connected)break}}
function openEdit(p){editing=p;$('#editPrompt').value=p.prompt;$('#editDialogue').value=p.dialogue;$('#editSfx').value=p.sfx;$('#editSeed').value=p.seed;$('#editRef').value=p.ref??0.7;$('#editMask').value='';$('#editDialog').hidden=false}
async function regenEdit(inpaint=false){if(!editing)return;editing.prompt=$('#editPrompt').value;editing.dialogue=$('#editDialogue').value;editing.sfx=$('#editSfx').value;editing.seed=Number($('#editSeed').value)||editing.seed;editing.ref=Number($('#editRef').value);if(inpaint){const image=state.images[editing.id],file=$('#editMask').files[0];if(!image||!file)return status('Generate the panel and choose a mask image first.');busy=true;try{const mask=await fileData(file);const data=await api('/inpaint',{image,mask,prompt:panelPrompt(editing),negative:'low quality, deformed, watermark, text',seed:editing.seed,steps:28,guidance:7.5});state.images[editing.id]=data.image;status('Masked area updated.');}catch(e){status(e.message)}finally{busy=false}}else await generatePanel(editing);$('#editDialog').hidden=true;renderDraw();save()}
async function exportCanvas(p){const src=state.images[p.id];if(!src)return null;const img=await loadImage(src),c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d');x.drawImage(img,0,0);if(p.dialogue){x.font=`700 ${Math.max(18,c.width*.035)}px Arial`;const pad=16,w=Math.min(c.width*.72,x.measureText(p.dialogue).width+pad*2),h=55;x.fillStyle='white';roundRect(x,c.width*.07,c.height*.06,w,h,26);x.fill();x.strokeStyle='#111';x.lineWidth=3;x.stroke();x.fillStyle='#111';x.textAlign='center';x.fillText(p.dialogue,c.width*.07+w/2,c.height*.06+36)}if(p.sfx){x.font=`900 ${Math.max(26,c.width*.06)}px Impact`;x.fillStyle='white';x.strokeStyle='#111';x.lineWidth=6;x.textAlign='right';x.strokeText(p.sfx,c.width*.94,c.height*.9);x.fillText(p.sfx,c.width*.94,c.height*.9)}return c}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));}
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image;i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
async function canvasBlob(c){return new Promise(r=>c.toBlob(r,'image/png'))}
async function downloadPanel(p){const c=await exportCanvas(p);if(!c)return;downloadBlob(await canvasBlob(c),`panel-${state.panels.indexOf(p)+1}.png`)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
async function exportPngs(){for(const p of state.panels)if(state.images[p.id])await downloadPanel(p)}
async function exportZip(){if(!window.JSZip)return status('ZIP library did not load. Try again online.');const zip=new JSZip();zip.file('project.json',JSON.stringify({...state,images:{}},null,2));let n=0;for(const p of state.panels){if(!state.images[p.id])continue;const blob=await canvasBlob(await exportCanvas(p));zip.file(`panels/${String(++n).padStart(3,'0')}.png`,blob)}for(const c of state.characters)if(c.reference)zip.file(`characters/${c.name.replace(/[^\w-]+/g,'_')}.png`,dataToBlob(c.reference));downloadBlob(await zip.generateAsync({type:'blob'}),`${safeName(state.name)}.zip`)}
function dataToBlob(data){const [meta,b64]=data.split(',');const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));return new Blob([bytes],{type:meta.match(/data:(.*?);/)?.[1]||'application/octet-stream'})}
async function exportWebtoon(){const canvases=[];for(const p of state.panels)if(state.images[p.id])canvases.push(await exportCanvas(p));if(!canvases.length)return status('Generate at least one panel first.');const gap=24,w=Math.max(...canvases.map(c=>c.width)),h=canvases.reduce((s,c)=>s+c.height,0)+gap*(canvases.length-1);if(h>32767)return status('Webtoon is too tall for one browser image. Export ZIP instead.');const out=document.createElement('canvas');out.width=w;out.height=h;const x=out.getContext('2d');x.fillStyle='#111';x.fillRect(0,0,w,h);let y=0;for(const c of canvases){x.drawImage(c,(w-c.width)/2,y);y+=c.height+gap}downloadBlob(await canvasBlob(out),`${safeName(state.name)}-webtoon.png`)}
async function exportPdf(){if(!window.jspdf)return status('PDF library did not load. Try again online.');const ready=state.panels.filter(p=>state.images[p.id]);if(!ready.length)return status('Generate at least one panel first.');let doc;for(let i=0;i<ready.length;i++){const c=await exportCanvas(ready[i]),data=c.toDataURL('image/jpeg',.92),orientation=c.width>c.height?'landscape':'portrait';if(!doc)doc=new jspdf.jsPDF({orientation,unit:'px',format:[c.width,c.height]});else doc.addPage([c.width,c.height],orientation);doc.addImage(data,'JPEG',0,0,c.width,c.height)}doc.save(`${safeName(state.name)}.pdf`)}
function safeName(s){return (s||'manga-project').replace(/[^\w-]+/g,'-').replace(/^-|-$/g,'').toLowerCase()||'manga-project'}
function newProject(){if(!confirm('Start a new project? Your saved project will be replaced when you save.'))return;state={name:'Untitled story',story:'',style:'manhwa',characters:[],scenes:[],panels:[],images:{},cover:null,version:1};$('#projectName').value=state.name;$('#story').value='';renderAll();go('story');status('New project ready.')}
$$('.stage').forEach(b=>b.onclick=()=>go(b.dataset.step));$$('[data-style]').forEach(b=>b.onclick=()=>selectStyle(b.dataset.style));
$('#story').oninput=()=>{renderStats();autosave()};$('#analyze').onclick=analyze;$('#exampleStory').onclick=()=>{$('#story').value=example;renderStats()};$('#clearStory').onclick=()=>{$('#story').value='';renderStats()};$('#importStory').onclick=()=>$('#storyFile').click();$('#storyFile').onchange=async e=>{if(e.target.files[0]){$('#story').value=await e.target.files[0].text();renderStats()}};$('#addCharacter').onclick=()=>{state.characters.push({id:uid('char'),name:'New character',role:'Character',description:'',outfit:'',traits:'',locked:false,reference:null,seed:Math.floor(Math.random()*2**31)});renderCast()};$('#autoLayout').onclick=autoLayout;$('#generateAll').onclick=()=>generateSet(state.panels);$('#generateMissing').onclick=()=>generateSet(state.panels.filter(p=>!state.images[p.id]));$('#connectImage').onclick=connect;$('#projectName').oninput=autosave;$('#saveProject').onclick=()=>{save();status('Project saved on this device.')};$('#loadProject').onclick=()=>{load();status('Saved project loaded.')};$('#newProject').onclick=newProject;$('#closeEdit').onclick=()=>$('#editDialog').hidden=true;$('#regenPanel').onclick=()=>regenEdit(false);$('#inpaintPanel').onclick=()=>regenEdit(true);$('#exportPngs').onclick=exportPngs;$('#exportZip').onclick=exportZip;$('#exportWebtoon').onclick=exportWebtoon;$('#exportPdf').onclick=exportPdf;
load();if(imageKey){sessionStorage.setItem('qt-image-key',imageKey);setTimeout(connect,100)}
